## How resturant recommendation system works

The rapid growth in data collection has led to a new era of a data driven world. Data is used to create more efficient systems and that's where recommendation systems comes in.

Recommendation systems are a type of information filtering systems because they improve qualty of serach and provide elements that are more relavant to search items or that are related to search history of user. 

These are active information filtering systems that personalize information provided to used based on thier intrest, relevance of information etc. Recommendation systems are widely used to recommend items, resturants, places to visit, items to buy etc.

There are two types of recommendation systems.

1. Content based filtering
2. Collabarative filtering

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, r2_score
import warnings
warnings.filterwarnings('always')
warnings.filterwarnings('ignore')
from nltk.corpus import stopwords
import re
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

Now I will load and read dataset.

In [2]:
zomato_real = pd.read_csv('C:\\Users\\bkumarsingh\\OneDrive - E2open, LLC\\Attachments\\AI\\Projects\\Kaggle\\Resturant Recommendation system\\zomato.csv')

In [3]:
zomato_real

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

Now, the next step is data cleansing and feature engineering, foe this step we need to do lot of stuff such as:

1. Deleting unnecessary column
2. Removing duplicates
3. Remove the NAN values from dataset
4. Changing the column names
5. Data transformations
6. Data cleaning
7. Adjust the column names

Now, lets perform above steps on our data.

In [4]:
# Deleting unnecessary column

zomato = zomato_real.drop(['url', 'dish_liked', 'phone'], axis=1)
zomato

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,Whitefield,Bar,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,Whitefield,Bar,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [5]:
# Removing duplicates

print(zomato.duplicated().sum())
zomato.drop_duplicates(inplace=True)

43

In [6]:
zomato

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,Whitefield,Bar,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,Whitefield,Bar,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [7]:
# Remove NAN values from dataset

print(zomato.isna().sum())
zomato.dropna(how='any', inplace=True)
zomato

address                           0
name                              0
online_order                      0
book_table                        0
rate                           7767
votes                             0
location                         21
rest_type                       227
cuisines                         45
approx_cost(for two people)     345
reviews_list                      0
menu_item                         0
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51709,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,No,No,3.7 /5,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",800,"[('Rated 4.0', 'RATED\n Ambience- Big and spa...",[],Pubs and bars,Whitefield
51711,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",800,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
51712,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51715,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [8]:
# Rename columns

zomato = zomato.rename(columns={'approx_cost(for two people)':'cost','listed_in(type)':'type', 'listed_in(city)':'city'})

In [9]:
zomato.name

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
51709                           The Farm House Bar n Grill
51711                                              Bhagini
51712    Best Brews - Four Points by Sheraton Bengaluru...
51715    Chime - Sheraton Grand Bengaluru Whitefield Ho...
51716                         The Nest - The Den Bengaluru
Name: name, Length: 43499, dtype: object

In [10]:
# See transformations

zomato['cost'] = zomato['cost'].astype(str) # Changing cost type to string

zomato['cost'] = zomato['cost'].apply(lambda x:x.replace(',', '.')) # Using lambda function to replace ',' from cost 

zomato['cost'] = zomato['cost'].astype(float)

# Removing /5 from rates

zomato = zomato.loc[zomato.rate != 'NEW']

zomato = zomato.loc[zomato.rate != '-'].reset_index(drop=True)

remove_slash = lambda x: x.replace('/5', '') if type(x) == np.str else x

zomato.rate = zomato.rate.apply(remove_slash).str.strip().astype(float)

# Adjust the column names

zomato.online_order.replace(('Yes', 'No'), (True, False), inplace=True)

zomato.book_table.replace(('Yes', 'No'), (True, False), inplace=True)

# Computing mean rating

resturants = list(zomato.name.unique())

zomato['mean_rating'] = 0

for i in range(len(resturants)):
    zomato['mean_rating'][zomato['name']==resturants[i]] = zomato['rate'][zomato['name']==resturants[i]].mean()

In [11]:
zomato

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost,reviews_list,menu_item,type,city,mean_rating
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,True,True,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.118182
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,True,False,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.100000
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,True,False,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.800000
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,False,False,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.700000
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,False,False,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41232,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,False,False,3.7,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",800.0,"[('Rated 4.0', 'RATED\n Ambience- Big and spa...",[],Pubs and bars,Whitefield,3.700000
41233,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,False,False,2.5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.283333
41234,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,27,Whitefield,Bar,Continental,1.5,"[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield,3.600000
41235,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,236,"ITPL Main Road, Whitefield",Bar,Finger Food,2.5,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.300000
41236,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,False,False,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental",1.5,"[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield,3.400000

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler = MinMaxScaler(feature_range=(1,5))

In [15]:
zomato[['mean_rating']] = scaler.fit_transform(zomato[['mean_rating']]).round(2)

In [16]:
zomato

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost,reviews_list,menu_item,type,city,mean_rating
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,True,True,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,3.99
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,True,False,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,3.97
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,True,False,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.58
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,False,False,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.45
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,False,False,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41232,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,False,False,3.7,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",800.0,"[('Rated 4.0', 'RATED\n Ambience- Big and spa...",[],Pubs and bars,Whitefield,3.45
41233,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,False,False,2.5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,1.62
41234,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,27,Whitefield,Bar,Continental,1.5,"[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield,3.32
41235,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,236,"ITPL Main Road, Whitefield",Bar,Finger Food,2.5,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.23
41236,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,False,False,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental",1.5,"[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield,3.06

Now, next step is to perform some text preprocessing steps which inlude:

1. Lower casing
2. Removal of Punctuation
3. Removal of stopwords
4. Removal of URLs
5. Spelling correction

Now, lets perform above text processing on data.

In [17]:
# Lower casing

zomato['reviews_list'] = zomato['reviews_list'].str.lower()

# Removal of punctuation

import string

PUNCT_TO_REMOVE = string.punctuation

print(PUNCT_TO_REMOVE)

def remove_punctuation(text):
    """Custom function to remove punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

zomato['reviews_list'] = zomato['reviews_list'].apply(lambda text:remove_punctuation(text))

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [18]:
zomato

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost,reviews_list,menu_item,type,city,mean_rating
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,True,True,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800.0,rated 40 ratedn a beautiful place to dine int...,[],Buffet,Banashankari,3.99
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,True,False,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800.0,rated 40 ratedn had been here for dinner with...,[],Buffet,Banashankari,3.97
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,True,False,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800.0,rated 30 ratedn ambience is not that good eno...,[],Buffet,Banashankari,3.58
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,False,False,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300.0,rated 40 ratedn great food and proper karnata...,[],Buffet,Banashankari,3.45
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,False,False,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600.0,rated 40 ratedn very good restaurant in neigh...,[],Buffet,Banashankari,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41232,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,False,False,3.7,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",800.0,rated 40 ratedn ambience big and spacious law...,[],Pubs and bars,Whitefield,3.45
41233,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,False,False,2.5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",800.0,rated 40 ratedn a fine place to chill after o...,[],Pubs and bars,Whitefield,1.62
41234,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,27,Whitefield,Bar,Continental,1.5,rated 50 ratedn food and service are incompar...,[],Pubs and bars,Whitefield,3.32
41235,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,236,"ITPL Main Road, Whitefield",Bar,Finger Food,2.5,rated 40 ratedn nice and friendly place and s...,[],Pubs and bars,Whitefield,4.23
41236,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,False,False,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental",1.5,rated 50 ratedn great ambience looking nice ...,[],Pubs and bars,Whitefield,3.06

In [20]:
# Removal of words

import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords

STOPWORDS = set(stopwords.words('english'))

def remove_stopwords(text):
    """Custom function to remove stopwords"""
    return ' '.join([word for word in str(text).split() if word not in STOPWORDS])

zomato['reviews_list'] = zomato['reviews_list'].apply(lambda text:remove_stopwords(text))

zomato

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bkumarsingh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost,reviews_list,menu_item,type,city,mean_rating
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,True,True,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800.0,rated 40 ratedn beautiful place dine inthe int...,[],Buffet,Banashankari,3.99
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,True,False,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800.0,rated 40 ratedn dinner family turned good choo...,[],Buffet,Banashankari,3.97
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,True,False,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800.0,rated 30 ratedn ambience good enough pocket fr...,[],Buffet,Banashankari,3.58
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,False,False,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300.0,rated 40 ratedn great food proper karnataka st...,[],Buffet,Banashankari,3.45
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,False,False,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600.0,rated 40 ratedn good restaurant neighbourhood ...,[],Buffet,Banashankari,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41232,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,False,False,3.7,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",800.0,rated 40 ratedn ambience big spacious lawn use...,[],Pubs and bars,Whitefield,3.45
41233,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,False,False,2.5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",800.0,rated 40 ratedn fine place chill office hours ...,[],Pubs and bars,Whitefield,1.62
41234,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,27,Whitefield,Bar,Continental,1.5,rated 50 ratedn food service incomparably exce...,[],Pubs and bars,Whitefield,3.32
41235,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,236,"ITPL Main Road, Whitefield",Bar,Finger Food,2.5,rated 40 ratedn nice friendly place staff awes...,[],Pubs and bars,Whitefield,4.23
41236,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,False,False,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental",1.5,rated 50 ratedn great ambience looking nice go...,[],Pubs and bars,Whitefield,3.06

In [21]:
# Removal of URLs

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

zomato['reviews_list'] = zomato['reviews_list'].apply(lambda text:remove_urls(text))

zomato

,address,name,online_order,book_table,rate,votes,location,rest_type,cuisines,cost,reviews_list,menu_item,type,city,mean_rating
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,True,True,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800.0,rated 40 ratedn beautiful place dine inthe int...,[],Buffet,Banashankari,3.99
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,True,False,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800.0,rated 40 ratedn dinner family turned good choo...,[],Buffet,Banashankari,3.97
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,True,False,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800.0,rated 30 ratedn ambience good enough pocket fr...,[],Buffet,Banashankari,3.58
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,False,False,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300.0,rated 40 ratedn great food proper karnataka st...,[],Buffet,Banashankari,3.45
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,False,False,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600.0,rated 40 ratedn good restaurant neighbourhood ...,[],Buffet,Banashankari,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41232,"136, SAP Labs India, KIADB Export Promotion In...",The Farm House Bar n Grill,False,False,3.7,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",800.0,rated 40 ratedn ambience big spacious lawn use...,[],Pubs and bars,Whitefield,3.45
41233,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,False,False,2.5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",800.0,rated 40 ratedn fine place chill office hours ...,[],Pubs and bars,Whitefield,1.62
41234,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,27,Whitefield,Bar,Continental,1.5,rated 50 ratedn food service incomparably exce...,[],Pubs and bars,Whitefield,3.32
41235,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,236,"ITPL Main Road, Whitefield",Bar,Finger Food,2.5,rated 40 ratedn nice friendly place staff awes...,[],Pubs and bars,Whitefield,4.23
41236,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,False,False,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental",1.5,rated 50 ratedn great ambience looking nice go...,[],Pubs and bars,Whitefield,3.06

In [22]:
zomato[['reviews_list', 'cuisines']]

,reviews_list,cuisines
0,rated 40 ratedn beautiful place dine inthe int...,"North Indian, Mughlai, Chinese"
1,rated 40 ratedn dinner family turned good choo...,"Chinese, North Indian, Thai"
2,rated 30 ratedn ambience good enough pocket fr...,"Cafe, Mexican, Italian"
3,rated 40 ratedn great food proper karnataka st...,"South Indian, North Indian"
4,rated 40 ratedn good restaurant neighbourhood ...,"North Indian, Rajasthani"
...,...,...
41232,rated 40 ratedn ambience big spacious lawn use...,"North Indian, Continental"
41233,rated 40 ratedn fine place chill office hours ...,"Andhra, South Indian, Chinese, North Indian"
41234,rated 50 ratedn food service incomparably exce...,Continental
41235,rated 40 ratedn nice friendly place staff awes...,Finger Food
41236,rated 50 ratedn great ambience looking nice go...,"Finger Food, North Indian, Continental"

In [23]:
# Resturant names

resturant_names = list(zomato['name'].unique())


def get_top_words(column, top_nu_of_words, nu_of_word):
    vec = CountVectorizer(ngram_range=nu_of_word, stop_words='english')
    print('vec=>', vec)
    bag_of_words = vec.fit_transform(column)
    print('bag_of_words', bag_of_words)
    sum_words = bag_of_words.sum(axis=0)
    print('sum_words', sum_words)
    word_freq = [(word, sum_words[0,idx]) for word, idx in vec.vocabulary_.items()]
    print('word_freq', word_freq)
    word_freq = sorted(word_freq, key=lambda x:x[1], reverse=True)
    print('word_freq', word_freq)
    return word_freq[:top_nu_of_words]

In [24]:
zomato = zomato.drop(['address', 'rest_type', 'type', 'menu_item', 'votes'], axis=1)

In [25]:
zomato

,name,online_order,book_table,rate,location,cuisines,cost,reviews_list,city,mean_rating
0,Jalsa,True,True,4.1,Banashankari,"North Indian, Mughlai, Chinese",800.0,rated 40 ratedn beautiful place dine inthe int...,Banashankari,3.99
1,Spice Elephant,True,False,4.1,Banashankari,"Chinese, North Indian, Thai",800.0,rated 40 ratedn dinner family turned good choo...,Banashankari,3.97
2,San Churro Cafe,True,False,3.8,Banashankari,"Cafe, Mexican, Italian",800.0,rated 30 ratedn ambience good enough pocket fr...,Banashankari,3.58
3,Addhuri Udupi Bhojana,False,False,3.7,Banashankari,"South Indian, North Indian",300.0,rated 40 ratedn great food proper karnataka st...,Banashankari,3.45
4,Grand Village,False,False,3.8,Basavanagudi,"North Indian, Rajasthani",600.0,rated 40 ratedn good restaurant neighbourhood ...,Banashankari,3.58
...,...,...,...,...,...,...,...,...,...,...
41232,The Farm House Bar n Grill,False,False,3.7,Whitefield,"North Indian, Continental",800.0,rated 40 ratedn ambience big spacious lawn use...,Whitefield,3.45
41233,Bhagini,False,False,2.5,Whitefield,"Andhra, South Indian, Chinese, North Indian",800.0,rated 40 ratedn fine place chill office hours ...,Whitefield,1.62
41234,Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,Whitefield,Continental,1.5,rated 50 ratedn food service incomparably exce...,Whitefield,3.32
41235,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,"ITPL Main Road, Whitefield",Finger Food,2.5,rated 40 ratedn nice friendly place staff awes...,Whitefield,4.23
41236,The Nest - The Den Bengaluru,False,False,3.4,"ITPL Main Road, Whitefield","Finger Food, North Indian, Continental",1.5,rated 50 ratedn great ambience looking nice go...,Whitefield,3.06

# TF-IDF Vectorization

TF-IDF (Term frequency Inverse document frequency) vectors for each document. This will give you a matrix where each column represet a word in general in vocabulary (all words that appear in atleast one document) and each column represents a resturant, as before. 

TF-IDF is a statistical method of accessing the meaning of a word in a given document. Now I will use TF-IDF vectorization on dataset.

In [26]:
df_percent = zomato.sample(frac=0.5)

In [28]:
df_percent.set_index('name', inplace=True)

In [29]:
df_percent

,online_order,book_table,rate,location,cuisines,cost,reviews_list,city,mean_rating
name,,,,,,,,,
CakeZone,True,False,3.8,"Varthur Main Road, Whitefield","Bakery, Desserts",200.0,rated 50 ratedn dont sweet tooth always prefer...,Brookefield,3.72
Ayda Persian Kitchen,True,False,3.9,Church Street,"North Indian, Iranian",950.0,rated 40 ratedn tiny hidden gem persian meat l...,Lavelle Road,3.65
Kolkatta Famous Chat,True,False,3.7,Indiranagar,"Street Food, North Indian",100.0,rated 30 ratedn place near stay typical north ...,Old Airport Road,3.45
Tasty Point,True,False,3.3,Bannerghatta Road,"Burger, Sandwich, Finger Food",300.0,rated 50 ratedn k fine rated 50 ratedn amazing...,JP Nagar,2.94
Fava,False,True,4.4,Lavelle Road,"Healthy Food, Mediterranean, Desserts, Italian...",1.2,rated 30 ratedn authentic mediterranean food s...,Brigade Road,4.35
...,...,...,...,...,...,...,...,...,...
Oldtown Dilli,True,True,4.1,Koramangala 4th Block,"Mughlai, North Indian, Turkish, Afghan",750.0,rated 50 ratedn best afghani chicken bangalore...,Koramangala 7th Block,3.97
Kerala Foods,False,False,3.5,Vasanth Nagar,Kerala,250.0,rated 50 ratedn well go kerala delicacies chea...,Frazer Town,3.19
Mojo Bites,False,False,3.9,Whitefield,Fast Food,250.0,rated 50 ratedn mojo bites hidden gem whitefie...,Whitefield,3.71
The Brew - Aurick Boutique Hotel,False,False,3.1,JP Nagar,"North Indian, South Indian, Chinese, Grill",700.0,rated 25 ratedn ordinary sit outnnot much view...,JP Nagar,2.68
The Kitchen Bandit,True,False,3.2,Koramangala 2nd Block,"Chinese, North Indian, Fast Food",350.0,rated 10 ratedn charge money food provided hor...,Koramangala 7th Block,2.81

In [30]:
indices = pd.Series(df_percent.index)

In [31]:
indices

0                                CakeZone
1                    Ayda Persian Kitchen
2                    Kolkatta Famous Chat
3                             Tasty Point
4                                    Fava
                       ...
20613                       Oldtown Dilli
20614                        Kerala Foods
20615                          Mojo Bites
20616    The Brew - Aurick Boutique Hotel
20617                  The Kitchen Bandit
Name: name, Length: 20618, dtype: object

In [32]:
# Creating TF-IDF matrix

tfidf = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0, stop_words='english')

tfidf_matrix = tfidf.fit_transform(df_percent['reviews_list'])
print(tfidf_matrix)
cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)
print(cosine_similarities)

  (0, 159184)	0.1402451764785979
  (0, 285843)	0.1367108479108026
  (0, 579287)	0.050996808104491254
  (0, 1057765)	0.15578034578388228
  (0, 1371289)	0.15578034578388228
  (0, 1229282)	0.15578034578388228
  (0, 330726)	0.06490283870678708
  (0, 586593)	0.12422262068303039
  (0, 775318)	0.07047214549687386
  (0, 1075044)	0.10139007097300333
  (0, 851625)	0.14480171849435697
  (0, 411561)	0.15578034578388228
  (0, 505736)	0.15578034578388228
  (0, 1231354)	0.09101903422512041
  (0, 1251211)	0.11324399339350508
  (0, 979625)	0.05467318974237757
  (0, 10456)	0.024464019862346868
  (0, 972004)	0.024446814550865784
  (0, 324125)	0.06869011346992832
  (0, 423445)	0.14236015498848903
  (0, 185663)	0.15122380376812322
  (0, 324871)	0.15578034578388228
  (0, 183509)	0.1476894752003279
  (0, 971117)	0.15578034578388228
  (0, 184384)	0.14480171849435697
  :	:
  (20617, 214865)	0.01874112762575302
  (20617, 763988)	0.01118594882458705
  (20617, 353467)	0.009420122697066857
  (20617, 450897)	0.09647233587909004
  (20617, 1054012)	0.017111579761686965
  (20617, 780251)	0.03247736406693045
  (20617, 523638)	0.006235699325918038
  (20617, 16009)	0.014988930614163707
  (20617, 775318)	0.03322168444895003
  (20617, 10456)	0.005766363025344436
  (20617, 972004)	0.005762307597310846
  (20617, 22661)	0.10267149496825209
  (20617, 972020)	0.10258006870067246
  (20617, 1225910)	0.012216709919471073
  (20617, 329330)	0.08275071332195938
  (20617, 586495)	0.022547211211925097
  (20617, 774939)	0.018937216447845864
  (20617, 851255)	0.025943897590969274
  (20617, 503525)	0.054051292919389676
  (20617, 1230862)	0.008694736245401596
  (20617, 10332)	0.005705375175489542
  (20617, 897281)	0.004655313378605504
  (20617, 972193)	0.16891263028451967
  (20617, 22519)	0.10208198823845742
  (20617, 971996)	0.1688880462148131
[[1.         0.01333342 0.00665618 ... 0.00568983 0.01274296 0.0291431 ]
 [0.01333342 1.         0.23373648 ... 0.01422934 0.02307756 0.21483951]
 [0.00665618 0.23373648 1.         ... 0.00588226 0.01342728 0.53378208]
 ...
 [0.00568983 0.01422934 0.00588226 ... 1.         0.00443601 0.01591873]
 [0.01274296 0.02307756 0.01342728 ... 0.00443601 1.         0.04559712]
 [0.0291431  0.21483951 0.53378208 ... 0.01591873 0.04559712 1.        ]]

Now, last step of creating resturant recommendation system is to write a function which will do resturant recommendation.

In [34]:
def recommend(name, cosine_similarities=cosine_similarities):
    
    # Create a list to put top resturants
    recommend_resturant = []
    
    # Find the index of the hotel entered
    idx = indices[indices==name].index[0]
    
    #Find the resturants with similar cosine similarity value and order them
    score_series = pd.Series(cosine_similarities[idx]).sort_values(ascending=False)
    
    #Extract top 30 resturant indexes with a similar cosine sim value
    top30_index = list(score_series.iloc[0:31].index)
    
    # Names of the top 30 resturant
    for i in top30_index:
        recommend_resturant.append(list(df_percent.index)[i])
        
    # Create the new dataset to show similar resturants
    df_new = pd.DataFrame(columns=['cuisines', 'mean_rating', 'cost'])
    
    # Create top 30 similar resturants with some of their columns
    for i in recommend_resturant:
        df_new = df_new.append(pd.DataFrame(df_percent[['cuisines', 'mean_rating', 'cost']][df_percent.index==i].sample()))
        
    # Drop the same name resturant and sort only the top 10 by the highest rating
    df_new = df_new.drop_duplicates(subset=['cuisines', 'mean_rating', 'cost'], keep=False)
    df_new = df_new.sort_values(by='mean_rating', ascending=False)
    print('TOP %s resturants like %s with similar reviews: ' %(str(len(df_new)), name))
    
    return df_new

In [35]:
recommend('Pai Vihar')

TOP 14 resturants like Pai Vihar with similar reviews:

,cuisines,mean_rating,cost
Burma Burma,"Asian, Burmese",4.74,1.5
Andhra Ruchulu,"Andhra, North Indian, Chinese, Biryani",3.72,500.0
Cafe Aladdin,"Cafe, Chinese",3.71,500.0
Dum Biryani Hub,Biryani,3.71,700.0
Wow Paratha,North Indian,3.71,400.0
Karavali Grand,"Mangalorean, Seafood, North Indian, Chinese",3.45,600.0
Chicken Corner,"Biryani, North Indian, Fast Food, Chinese",3.35,400.0
Queen Pearls,Pizza,3.32,500.0
On The Nose,"Cafe, Italian, Mexican, Chinese",3.27,600.0
Karavali Family Restaurant,"Seafood, Biryani, South Indian, North Indian, ...",3.19,500.0
Currylicious,"South Indian, Mangalorean, Kerala",2.81,800.0
Amaravati Authentic Andhra Restaurant,"Andhra, Chinese, North Indian, Biryani",2.57,600.0
Corprate Biriyani Adda,"North Indian, Chinese",2.55,500.0
Red Chilli,"Chinese, Thai",2.55,600.0